"""Create corrected_texts table

Revision ID: 721b53716737
Revises: 
Create Date: 2025-02-03 22:08:18.185747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '721b53716737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corrected_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('corrected_text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('corrected_texts')
    # ### end Alembic commands ###
